services:
  web:
    build: .
    container_name: family_tree_web
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000 (Uvicorn default)
    volumes:
      - .:/app # Mount the current directory to /app in the container for live code changes
      - ./logs:/app/logs # Mount logs directory
      # Persist SQLite database file outside the container
      # Note: For production, consider a more robust database solution (PostgreSQL, MySQL)
      # and manage its data volume separately.
      - ./data:/app/data # Mount a data directory for the SQLite DB
    environment:
      # Load environment variables from .env file
      - APP_ENV=development # Use APP_ENV for FastAPI config
      # Override database URI to use the mounted volume with async prefix
      - DATABASE_URL=sqlite+aiosqlite:////app/data/app.db
      # Initial Admin User Credentials (Change for production!)
      - INITIAL_ADMIN_USERNAME=admin
      - INITIAL_ADMIN_EMAIL=admin@example.com
      - INITIAL_ADMIN_PASSWORD=changeme # <-- IMPORTANT: Change this!
      # You can add other environment variables here or load from an .env file
      # env_file:
      #   - .env
    # depends_on:
      # - db # If you were using a separate database container
    restart: unless-stopped

# Optional: Define a volume for the database if not mounting a host directory
# volumes:
#   app_data:

  frontend:
    build:
      context: ./frontend # Path to the frontend directory
      dockerfile: Dockerfile
    container_name: family_tree_frontend
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000 (serve default)
    volumes:
      # Mount source code for development (optional, remove for production build)
      # Note: Changes won't reflect immediately due to build stage unless dev server is used in Dockerfile
      - ./frontend/src:/app/src
    environment:
      # Ensure Node environment is set if needed by build tools
      - NODE_ENV=development
      # Point API requests to the backend service within Docker network
      # This requires updating the frontend code to use this variable
      - VITE_API_BASE_URL=http://web:8000/api
    depends_on:
      - web # Frontend depends on the backend API
    restart: unless-stopped