services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: family_tree_backend
    env_file:
      - .env # Load variables from .env file
    environment:
      # Define DATABASE_URL for SQLite, pointing inside the container volume
      DATABASE_URL: sqlite+aiosqlite:////db_data/app.db
      APP_ENV: ${APP_ENV:-production} # Default to production if not set
    volumes:
      - app_logs:/app/logs # Mount named volume for logs
      - ./db_data:/db_data # Mount host directory for SQLite DB file
      # No code mounting for production
    # No database dependency needed for SQLite
    restart: unless-stopped
    # Healthcheck is defined in the backend Dockerfile

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: family_tree_frontend
    ports:
      - "443:443"
    depends_on:
      - backend # Optional, depends if frontend needs backend at build time (it doesn't here)
    restart: unless-stopped

volumes:
  app_logs:
    driver: local
