services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: ${UID}
        HOST_GID: ${GID}
    env_file:
      - .env
    environment:
      PYTHONPATH: "/app"
      DATABASE_URL: "sqlite:///db_data/app.db"
    volumes:
      - ./:/app
      - ./db_data:/db_data
      - app_logs:/app/logs

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        CADDY_FILE: Caddyfile.dev
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./frontend:/app/frontend

volumes:
  app_logs:
    driver: local
