services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: ${UID}
        HOST_GID: ${GID}
    env_file:
      - .env_local
    environment:
      PYTHONPATH: "/app"
      DATABASE_URL: "sqlite:///db_data/app.db"
    volumes:
      - ./:/app
      - ./db_data:/db_data
      - ./logs:/app/logs

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      VITE_API_BASE_URL: /api
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - backend

volumes:
  node_modules:
