services:
  backend:
    volumes:
      - ./:/app
      - ./db_data:/app/db_data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        CADDY_FILE: Caddyfile.dev # Ensures Caddy uses the dev config
    ports:
      - "443:443" # HTTPS for Caddy
      - "80:80"   # HTTP (for redirect to HTTPS by Caddy, or direct access if Caddy is configured for it)
    volumes:
      # Mount frontend source files for live reloading with Vite HMR.
      # Assumes the frontend container's WORKDIR is /app and Vite serves from there.
      - ./frontend:/app/frontend
