"""Add admin_users table

Revision ID: 9458caf430d3
Revises: f14f92e97ea3
Create Date: 2025-04-25 20:50:20.704737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9458caf430d3'
down_revision: Union[str, None] = 'f14f92e97ea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'updated_at')
    # ### end Alembic commands ###