"""Add subscribed_emails table

Revision ID: f14f92e97ea3
Revises: 1fc8568adbf8
Create Date: 2025-04-25 20:30:33.258827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f14f92e97ea3'
down_revision: Union[str, None] = '1fc8568adbf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###